(*
  Each new term in the Fibonacci sequence is generated by adding the previous two terms.
  By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  Find the sum of all the even-valued terms in the sequence which do not exceed four million.
*)

let rec loop fib_a fib_b accum =
  let new_fib = fib_a + fib_b in
  if new_fib > 4000000 then accum
  else if (new_fib mod 2) = 0 then loop fib_b new_fib (accum + new_fib)
  else loop fib_b new_fib accum

let _ =
  print_int (loop 1 1 0); print_newline ()
